# general settings
name: JPEG_001_SCUNet
model_type: SRModel
scale: 1
num_gpu: auto  # set num_gpu: 0 for cpu mode
manual_seed: 1234

datasets:
  train:
    name: NTIRE_JPEG
    type: NTIREJPEGDataset
    dataroot_gt: /dataset/SR/SR_Image_Mix/DIV2K_train_HR
    dataroot_DIV8K: /dataset/SR/SR_Image_Mix/DIV8K
    dataroot_Flicker2K: /dataset/SR/SR_Image_Mix/Flicker2K
    dataroot_Unsplash2K: /dataset/SR/SR_Image_Mix/Unsplash2K
    dataroot_LSDIR: /dataset/SR/LSDIR_Dataset
    dataroot_nomos8k: /dataset/SR/nomos8k
    dataroot_nomos_uni_gt: /dataset/SR/nomos_uni_gt

    io_backend:
      type: disk

    gt_size: 128
    use_hflip: true
    use_rot: true

    # data loader
    num_worker_per_gpu: 8 # 4
    batch_size_per_gpu: 16 # 48
    dataset_enlarge_ratio: 1
    prefetch_mode: ~

  val:
    name: NTIRE_JPEG
    type: NTIREJPEGDataset
    dataroot_gt: /dataset/SR/DIV2K_0001_0020
    io_backend:
      type: disk

# network structures
network_g:
  type: SCUNet
  config: [4, 4, 6, 8, 6, 6, 4]
  dim: 96

# path
path:
  pretrain_network_g: ~ # experiments/001_RRDB/net_g_85000.pth
  param_key_g: params_ema
  strict_load_g: true
  resume_state: ~

# training settings
train:
  ema_decay: 0.999
  optim_g:
    type: Adam
    lr: !!float 1e-4
    weight_decay: 0
    betas: [0.9, 0.99]

  scheduler:
    type: MultiStepLR
    milestones: [300000, 600000]
    gamma: 0.5

  total_iter: 900000
  warmup_iter: -1  # no warm up

  # losses
  pixel_opt:
    type: L1Loss
    loss_weight: 1.0
    reduction: mean

#  QF_lossfn_opt:
#    type: L1Loss
#    loss_weight: 0.001
#    reduction: mean

#  psnr_opt:
#    type: PSNRLoss
#    loss_weight: 1.0
#    reduction: mean

# validation settings
val:
#  val_freq: 10
  val_freq: !!float 2e3
  save_img: false
  pbar: true

  metrics:
    psnr: # metric name, can be arbitrary
      type: calculate_psnr
      crop_border: 0
      test_y_channel: false

# logging settings
logger:
  print_freq: 100
  save_checkpoint_freq: !!float 2e3
  use_tb_logger: false
  wandb:
    project: ~
    resume_id: ~

# dist training settings
dist_params:
  backend: nccl
  port: 29500
